[licenses]
allow = ["Apache-2.0", "MIT", "Unicode-3.0"]
private = { ignore = true }

[advisories]
yanked = "deny"
ignore = [
    # bincode is deprecated -- just a dev-dependency in this crate
    "RUSTSEC-2025-0141",
    # proc-macro-error2 is unmaintained, via defmt
    "RUSTSEC-2026-0173",
]

[sources]
allow-git = [
    "https://github.com/strict-rs/strict-bincode",
    "https://github.com/earthlings-dev/strict-standard-rs.git",
    "https://github.com/earthlings-dev/strict-test-support-rs.git",
    "https://github.com/earthlings-dev/template-rs.git",
    "https://github.com/microsoft/windows-rs.git",
    "https://github.com/strict-rs/strict-bpaf.git",
    "https://github.com/strict-rs/strict-thiserror.git",
]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
